;; Migrated to vertico
;; (ido-everywhere t)
;; (ido-mode t)
;; (setq ido-enable-flex-matching t)
;; (setq ido-use-filename-at-point 'guess)
;; (setq ido-create-new-buffer 'always)
;; (rc/require 'ido-completing-read+)
;; (ido-ubiquitous-mode)
;; (rc/require 'smex)
;; (global-set-key (kbd "M-x") 'smex)
;; (global-set-key (kbd "M-X") 'smex-major-mode-commands)
;; (global-set-key (kbd "C-c C-c M-x") 'execute-extended-command)
