set -g status-keys emacs
set -g mode-keys emacs
set -g status-style bg='#000080'
bind-key -T copy-mode M-w send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

#unbind C-b
#set -g prefix C-x
#bind C-x send-prefix
