#!/usr/bin/env bash
LEVEL=$(cat /sys/class/power_supply/BAT*/capacity 2>/dev/null)
STATUS=$(cat /sys/class/power_supply/BAT*/status 2>/dev/null)

echo "Dust: ${LEVEL}% ${STATUS}"
echo "Dust: ${LEVEL}%"
if [ "$STATUS" = "Charging" ]; then
    echo "#00FF00"
elif [ "$LEVEL" -le 20 ]; then
    echo "#FF0000"
else
    echo "#FFFFFF"
fi

