#!/usr/bin/env bash

NVIM_PLUGIN_DIR="$HOME/.config/nvim/pack/plugins/start"

packer() {
    mkdir -p "$NVIM_PLUGIN_DIR"
    local plugin="$1"
    git clone "https://github.com/$plugin.git" "$NVIM_PLUGIN_DIR/$(basename "$plugin")"
    echo "Installed plugin: $plugin"
}
update() {
    for dir in "$NVIM_PLUGIN_DIR"/*; do
        if [ -d "$dir/.git" ]; then
            (cd "$dir" && git pull)
            echo "Updated plugin: $(basename "$dir")"
        fi
    done
}
remove() {
    local plugin_name="$1"
    rm -rf "$NVIM_PLUGIN_DIR/$plugin_name"
    echo "Removed plugin: $plugin_name"
}

if [ "$1" == "update" ]; then
    for dir in "$NVIM_PLUGIN_DIR"/*; do
        if [ -d "$dir/.git" ]; then
            plugin_name=$(basename "$dir")
            packer "$plugin_name" "update"
        fi
    done
    exit
fi

packer "echasnovski/mini.pick"
packer "chomosuke/typst-preview.nvim"
packer "neovim/nvim-lspconfig"
