#!/bin/sh
#!/bin/sh
set -e

USER=xsoder
HOME=/home/$USER
export USER HOME

# Graphical session environment
PID=$(pgrep -u $USER -n gnome-session) || PID=$(pgrep -u $USER -n kdeinit5) || exit 1
export DISPLAY=$(tr '\0' '\n' < /proc/$PID/environ | grep '^DISPLAY=' | cut -d= -f2)
export DBUS_SESSION_BUS_ADDRESS=$(tr '\0' '\n' < /proc/$PID/environ | grep '^DBUS_SESSION_BUS_ADDRESS=' | cut -d= -f2)
export XDG_RUNTIME_DIR=$(tr '\0' '\n' < /proc/$PID/environ | grep '^XDG_RUNTIME_DIR=' | cut -d= -f2)
export XAUTHORITY=$HOME/.Xauthority

# Fontconfig and XDG paths
export FONTCONFIG_PATH=/etc/fonts
export FONTCONFIG_FILE=/etc/fonts/fonts.conf
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config

# Locale
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# Path
export PATH=/usr/local/bin:/usr/bin:/bin:$HOME/.local/bin

# Load user profile
[ -f "$HOME/.profile" ] && . "$HOME/.profile"

# Start daemon
exec emacs --daemon 2>&1
