(deftheme cmp-darker
  "A cmp-darker theme based on Casey Muratori's editor colors.")
(let ((class '((class color) (min-colors 89)))
      (bg        "#161616")
      (fg        "#ffffff")
      (cursor    "#40FF40")
      (hl-line   "#101040")
      (selection "#3a3a8f")
      (bracket   "#cdaa7d")
      (string    "#6b8e23")
      (comment   "#7f7f7f")
      (keyword   "#cd950c")
      (constant  "#6b8e23")
      (invalid   "#f44747")
      (command   "#61afef")
      (purple    "#654CA8"))
  (custom-theme-set-faces
   'cmp-darker
   `(default ((,class (:background ,bg :foreground ,fg))))
   `(cursor ((,class (:background ,cursor))))
   `(hl-line ((,class (:background ,hl-line))))
   `(region ((,class (:background ,selection))))
   `(highlight ((,class (:background ,selection))))
   `(fringe ((,class (:background ,bg :foreground ,fg))))
   `(show-paren-match ((,class (:background ,purple :foreground ,fg :weight bold))))
   `(show-paren-mismatch ((,class (:background ,invalid :foreground ,fg :weight bold))))
   `(isearch ((,class (:background ,purple :foreground ,fg :weight bold))))
   `(lazy-highlight ((,class (:background ,purple :foreground ,fg :weight normal))))
   `(isearch-fail ((,class (:background ,invalid :foreground ,fg :weight bold))))
   `(font-lock-keyword-face       ((,class (:foreground ,keyword :weight bold :slant normal))))
   `(font-lock-builtin-face       ((,class (:foreground ,bracket :slant normal))))
   `(font-lock-type-face          ((,class (:foreground ,bracket :slant normal))))
   `(font-lock-variable-name-face ((,class (:foreground ,bracket :slant normal))))
   `(font-lock-function-name-face ((,class (:foreground ,bracket :slant normal))))
   `(font-lock-constant-face      ((,class (:foreground ,constant :slant normal))))
   `(font-lock-string-face        ((,class (:foreground ,string :slant normal))))
   `(font-lock-comment-face       ((,class (:foreground ,comment :slant normal))))
   `(font-lock-warning-face       ((,class (:foreground ,invalid :weight bold :slant normal))))
   `(minibuffer-prompt ((,class (:foreground ,keyword :weight bold :slant normal))))
   `(completions-common-part ((,class (:foreground ,command :weight normal :slant normal))))
   `(completions-first-difference ((,class (:foreground ,cursor :weight bold :slant normal))))
   `(completions-highlight ((,class (:background ,cursor :foreground ,bg :slant normal))))
   `(vertico-current ((,class (:background ,hl-line :foreground ,fg :weight normal))))
   ;; `(vertico-current ((,class (:foreground ,fg :weight bold :slant normal))))
   `(ivy-current-match ((,class (:background ,cursor :foreground ,bg :slant normal))))
   `(icomplete-first-match ((,class (:foreground ,command :weight bold :slant normal))))
   `(ido-first-match ((,class (:foreground ,cursor :weight bold :slant normal))))
   `(ido-only-match  ((,class (:foreground ,cursor :weight bold :slant normal))))
   `(ido-subdir      ((,class (:foreground ,command :weight bold :slant normal))))
   `(ido-indicator   ((,class (:foreground ,keyword :weight normal :slant normal))))
   `(ido-incomplete-regexp ((,class (:foreground ,invalid :weight bold :slant normal))))
   `(ido-virtual ((,class (:foreground ,comment :slant normal))))
   `(smex-item-selected ((,class (:background ,cursor :foreground ,bg :weight bold :slant normal))))
   `(smex-keyword ((,class (:foreground ,command :weight normal :slant normal))))
   `(compilation-info ((,class (:foreground ,command :weight normal :slant normal))))
   `(help-key-binding ((,class (:foreground ,command :weight normal :slant normal))))
   `(dired-directory ((,class (:foreground ,command :weight bold :slant normal))))
   `(dired-symlink   ((,class (:foreground ,keyword :weight normal :slant normal))))
   `(dired-marked    ((,class (:foreground ,cursor :weight bold :slant normal))))
   `(dired-flagged   ((,class (:foreground ,invalid :weight bold :slant normal))))
   `(dired-header    ((,class (:foreground ,cursor :weight bold))))
   `(dired-warning   ((,class (:foreground ,invalid :weight bold))))
   `(dired-set-id    ((,class (:foreground ,cursor :weight bold))))
   `(dired-special   ((,class (:foreground ,purple :weight bold))))
   `(whitespace-space ((,class (:foreground "#404040"))))
   `(whitespace-tab ((,class (:foreground "#404040"))))
   `(whitespace-newline ((,class (:foreground "#404040"))))
   `(whitespace-trailing ((,class (:background ,invalid :foreground ,fg))))
   `(mode-line ((,class (:background ,bg :foreground ,fg :box (:line-width -1 :color)))))
   `(mode-line-inactive ((,class (:background ,bg :foreground ,comment :box (:line-width -1 :color)))))
   `(whitespace-empty ((,class (:foreground "#404040"))))
   `(line-number ((,class (:foreground ,comment :inherit default))))
   `(line-number-current-line ((,class (:foreground ,keyword :weight bold :inherit default))))

   `(magit-section-heading ((,class (:foreground ,keyword :weight bold))))
   `(magit-section-highlight ((,class (:background ,hl-line))))
   `(magit-section-heading-selection ((,class (:foreground ,keyword :background ,selection :weight bold))))

   `(magit-diff-file-heading ((,class (:foreground ,bracket :weight bold))))
   `(magit-diff-file-heading-highlight ((,class (:foreground ,bracket :background ,hl-line :weight bold))))
   `(magit-diff-file-heading-selection ((,class (:foreground ,bracket :background ,selection :weight bold))))
   `(magit-diff-hunk-heading ((,class (:foreground ,command :background ,hl-line))))
   `(magit-diff-hunk-heading-highlight ((,class (:foreground ,command :background ,selection))))
   `(magit-diff-hunk-heading-selection ((,class (:foreground ,command :background ,selection :weight bold))))
   `(magit-diff-context ((,class (:foreground ,comment))))
   `(magit-diff-context-highlight ((,class (:foreground ,fg :background ,hl-line))))
   `(magit-diff-added ((,class (:foreground ,cursor :background "#0f2f0f"))))
   `(magit-diff-added-highlight ((,class (:foreground ,cursor :background "#1a3f1a"))))
   `(magit-diff-removed ((,class (:foreground ,invalid :background "#2f0f0f"))))
   `(magit-diff-removed-highlight ((,class (:foreground ,invalid :background "#3f1a1a"))))
   `(magit-diff-lines-heading ((,class (:foreground ,fg :background ,purple :weight bold))))

   `(magit-dimmed ((,class (:foreground ,comment))))
   `(magit-hash ((,class (:foreground ,purple))))
   `(magit-tag ((,class (:foreground ,keyword :weight bold))))
   `(magit-branch-local ((,class (:foreground ,command :weight bold))))
   `(magit-branch-remote ((,class (:foreground ,string :weight bold))))
   `(magit-branch-current ((,class (:foreground ,cursor :weight bold :box t))))
   `(magit-head ((,class (:foreground ,command :weight bold))))
   `(magit-refname ((,class (:foreground ,comment :weight bold))))
   `(magit-refname-stash ((,class (:foreground ,comment :weight bold))))
   `(magit-refname-wip ((,class (:foreground ,comment :weight bold))))
   `(magit-signature-good ((,class (:foreground ,cursor))))
   `(magit-signature-bad ((,class (:foreground ,invalid :weight bold))))
   `(magit-signature-untrusted ((,class (:foreground ,keyword))))
   `(magit-signature-expired ((,class (:foreground ,keyword))))
   `(magit-signature-revoked ((,class (:foreground ,invalid))))
   `(magit-signature-error ((,class (:foreground ,invalid))))
   `(magit-cherry-unmatched ((,class (:foreground ,command))))
   `(magit-cherry-equivalent ((,class (:foreground ,purple))))

   `(magit-log-author ((,class (:foreground ,bracket))))
   `(magit-log-date ((,class (:foreground ,comment))))
   `(magit-log-graph ((,class (:foreground ,comment))))

   `(magit-sequence-pick ((,class (:foreground ,fg))))
   `(magit-sequence-stop ((,class (:foreground ,cursor))))
   `(magit-sequence-part ((,class (:foreground ,keyword))))
   `(magit-sequence-head ((,class (:foreground ,command))))
   `(magit-sequence-drop ((,class (:foreground ,invalid))))
   `(magit-sequence-done ((,class (:foreground ,comment))))
   `(magit-sequence-onto ((,class (:foreground ,comment))))

   `(magit-bisect-good ((,class (:foreground ,cursor))))
   `(magit-bisect-skip ((,class (:foreground ,keyword))))
   `(magit-bisect-bad ((,class (:foreground ,invalid))))

   `(magit-blame-heading ((,class (:background ,hl-line :foreground ,fg))))
   `(magit-blame-hash ((,class (:background ,hl-line :foreground ,purple))))
   `(magit-blame-name ((,class (:background ,hl-line :foreground ,bracket))))
   `(magit-blame-date ((,class (:background ,hl-line :foreground ,comment))))
   `(magit-blame-summary ((,class (:background ,hl-line :foreground ,fg))))

   `(magit-process-ok ((,class (:foreground ,cursor :weight bold))))
   `(magit-process-ng ((,class (:foreground ,invalid :weight bold))))

   `(magit-section-secondary-heading ((,class (:foreground ,bracket :weight bold))))
   ))

(provide-theme 'cmp-darker)
