(deftheme cute
  "A cute dark theme with colorful highlights")

(custom-theme-set-faces
 'cute
 '(default                      ((t (:background "gray10"       :foreground "ivory"        ))))
 '(cursor                       ((t (:background "forest green" :foreground "midnight blue"))))
 '(hl-line                      ((t (:background "gray20"                                  ))))
 '(region                       ((t (:background "gray30"                                  ))))
 '(highlight                    ((t (:background "gray30"                                  ))))
 '(show-paren-match             ((t (:foreground "sky blue"                                ))))
 '(show-paren-mismatch          ((t (:foreground "medium purple"                           ))))
 '(isearch                      ((t (:background "gray10"     :foreground "plum"           ))))
 '(lazy-highlight               ((t (:background "misty rose" :foreground "gray10"         ))))
 '(isearch-fail                 ((t (:background "misty rose" :foreground "gray10"         ))))
 '(font-lock-keyword-face       ((t (:foreground "yellow"                                  ))))
 '(font-lock-builtin-face       ((t (:foreground "sky blue"                                ))))
 '(font-lock-type-face          ((t (:foreground "sky blue"                                ))))
 '(font-lock-variable-name-face ((t (:foreground "yellow"                                  ))))
 '(font-lock-function-name-face ((t (:foreground "yellow"                                  ))))
 '(font-lock-constant-face      ((t (:foreground "violet"                                  ))))
 '(font-lock-string-face        ((t (:foreground "gray80"                                  ))))
 '(font-lock-comment-face       ((t (:background "gray20"     :foreground "SpringGreen1"   ))))
 '(font-lock-warning-face       ((t (:foreground "DarkGoldenrod1"                          ))))
 '(minibuffer-prompt            ((t (:foreground "DarkGoldenrod1"                          ))))
 '(completions-highlight        ((t (:foreground "gray70"                                  ))))
 '(ido-first-match              ((t (:foreground "sky blue"                                ))))
 '(ido-only-match               ((t (:foreground "sky blue"                                ))))
 '(ido-subdir                   ((t (:foreground "RoyalBlue1"                              ))))
 '(ido-indicator                ((t (:foreground "gray20"                                  ))))
 '(ido-incomplete-regexp        ((t (:foreground "gray50"                                  ))))
 '(ido-virtual                  ((t (:foreground "gray60"                                  ))))
 '(compilation-info             ((t (:foreground "purple"                                  ))))
 '(help-key-binding             ((t (:foreground "purple"                                  ))))
 '(dired-directory              ((t (:foreground "sky blue"                                ))))
 '(dired-symlink                ((t (:foreground "SpringGreen1"                            ))))
 '(dired-marked                 ((t (:foreground "DarkGoldenrod1"                          ))))
 '(dired-flagged                ((t (:foreground "DarkGoldenrod3"                          ))))
 '(dired-header                 ((t (:foreground "sky blue"                                ))))
 '(dired-warning                ((t (:foreground "red"                                     ))))
 '(dired-set-id                 ((t (:foreground "orange"                                  ))))
 '(dired-special                ((t (:foreground "SpringGreen1"                            )))))

(provide-theme 'cute)
